# config/config.yaml
device: cuda
log_level: info
save_intermediate: false
input_video: data/videos/airport.mov
output_video: output/airport_output_tracked_desc_matching.mp4

detection:
  model_path: yolov8m.pt
  confidence_threshold: 0.4

tracking:
  tracker_cfg: config/bytetrack.yaml
  persist: True

embedding:
  model_path: openai/clip-vit-base-patch16
  similarity_threshold: 0.8

description:
  vlm_model: moondream
  description_similarity_threshold: 0.6

llm:
  llm_model: Qwen/Qwen2.5-7B-Instruct
  quant: 4bit            # "4bit" or "fp16"
  max_new_tokens: 120
